BrediusRollers/BrediusRollers/Core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('PAGES.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns() 

BrediusRollers/BrediusRollers/PAGES/urls.py
from django.urls import path
from . import views

app_name='Pages'

urlpatterns = [
    path('', views.home, name='home'),
    path('wedstrijden', views.wedstrijden, name='wedstrijden'),
    path('wedstrijden/<int:game_id>', views.wedstrijd, name='wedstrijd'),
    path('teams', views.teams, name='teams'),
    path('teams/<int:player_id>', views.player, name='player'),
    path('over-ons', views.overons, name='overons'),
    path('contact', views.contact, name='contact'),
]

BrediusRollers/BrediusRollers/accounts/urls.py
from django.urls import path
from . import views
from accounts.views import LoginView, RegisterView
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView

app_name='Accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/', views.profile, name='profile'),
    path('team/', views.team, name='team'),
    path('account_games/', views.account_games, name='account_games'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password-change/', views.ChangePasswordView.as_view(), name='password_change'),
]

BrediusRollers/BrediusRollers/accounts/models.py
from django.db import models
from django.contrib.auth.models import (
    AbstractBaseUser, BaseUserManager
)

class UserManager(BaseUserManager):
    def create_user(self, email, password=None, is_active=True, is_staff=False, is_admin=False):
        if not email:
            raise ValueError("Email is verplicht")
        if not password:
            raise ValueError("Wachtwoord is verplicht")

        user_obj = self.model(
            email = self.normalize_email(email),
        )
        user_obj.set_password(password)
        user_obj.staff = is_staff
        user_obj.admin = is_admin
        user_obj.active = is_active
        user_obj.save(using=self._db)
        return user_obj

    def create_staffuser(self, email, password=None):
        user = self.create_user(
            email,
            password=password,
            is_staff=True
        )
        return user
    
    def create_superuser(self, email, password=None):
        user = self.create_user(
            email,
            password=password,
            is_staff=True,
            is_admin=True
        )
        return user


class User(AbstractBaseUser):
    email       = models.EmailField(unique=True, max_length=128, verbose_name="Email")

    date_joined = models.DateTimeField(auto_now_add=True, verbose_name="Account aangemaakt")
    last_login  = models.DateTimeField(auto_now=True, verbose_name="Laatst online")

    active      = models.BooleanField(default=True)
    staff       = models.BooleanField(default=False)
    admin       = models.BooleanField(default=False)

    USERNAME_FIELD  = "email"
    REQUIRED_FIELDS = []

    objects = UserManager()

    def __str__(self):
        return self.email


    def formated_date_joined(self):
        date = self.date_joined
        return date.strftime("%d %b %y om %H:%M")

    def formated_last_login(self):
        date = self.last_login
        return date.strftime("%d %b %y om %H:%M")


    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.staff

    @property
    def is_admin(self):
        return self.admin

    @property
    def is_active(self):
        return self.active

BrediusRollers/BrediusRollers/teams/models.py
from django.contrib import admin
from django.db import models
from django.urls import reverse
from multiselectfield import MultiSelectField
from accounts.model.profile import Profile
from club.models import Season, Club, Coach
from datetime import date

class League(models.Model):
    LEAGUE_CHOICES = [
        ('Hoofdklasse', 'Hoofdklasse'),
        ('Overgangsklasse', 'Overgangsklasse'),
        ('Eerste Klasse', 'Eerste Klasse'),
        ('Tweede Klasse', 'Tweede Klasse'),
        ('Derde Klasse', 'Derde Klasse'),
        ('Vierde Klasse', 'Vierde Klasse'),
    ]
    name = models.CharField(choices=LEAGUE_CHOICES, max_length=50, verbose_name="League")
    def __str__(self):
        return self.name

class Team(models.Model):
    club = models.ForeignKey(Club, on_delete=models.CASCADE, null=True, blank=True, verbose_name="Club", limit_choices_to={'season__start_date__lte': date.today(), 'season__end_date__gte': date.today()})
    league = models.ForeignKey('teams.League', on_delete=models.CASCADE, verbose_name="League")
    name  = models.CharField(max_length=255, verbose_name="Team")
    
    points_earned  = models.IntegerField(verbose_name="Earned Points")
    matches_played  = models.IntegerField(verbose_name="Played Matches")
    coach = models.ForeignKey(Coach, on_delete=models.CASCADE, null=True, blank=True, verbose_name="Coach", limit_choices_to={'season__start_date__lte': date.today(), 'season__end_date__gte': date.today()})

    def __str__(self):
        return f"{self.club} {self.name}"

    def get_name(self):
        return f"{self.club.name} {self.name}"

    def get_absolute_url(self):
        return reverse('Pages:team_filter', args=[self.id])

class Player(models.Model):
    POSITION_CHOICES = [
        ('middenvelder', 'Middenvelder'),
        ('aanvaller', 'Aanvaller'),
        ('verdediger', 'Verdediger'),
        ('goalkeeper', 'Goalkeeper'),
    ]

    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True, verbose_name="Profile")
    team = models.ForeignKey(Team, on_delete=models.CASCADE, null=True, blank=True, verbose_name="Team", limit_choices_to={'club__season__start_date__lte': date.today(), 'club__season__end_date__gte': date.today()})
    positions = MultiSelectField(choices=POSITION_CHOICES, verbose_name="Positions")
    number_plate  = models.IntegerField(verbose_name="Number plate")

    is_captain  = models.BooleanField(blank=True, verbose_name="captain")

    def __str__(self):
        return self.profile.firstname + ' ' + self.profile.lastname

    def calculate_total_goals_current_season(self):
        current_date = date.today()
        current_season = Season.objects.get(start_date__lte=current_date, end_date__gte=current_date)
        return self.score_set.filter(season=current_season).aggregate(total_goals=models.Sum('goals'))['total_goals']

BrediusRollers/BrediusRollers/accounts/forms.py
from inspect import Attribute
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.contrib.auth import get_user_model
from .model.profile import Profile
from .model.adress import Adress

User = get_user_model()

class LoginForm(forms.Form):
    email    = forms.EmailField(widget=forms.TextInput(attrs={'name': 'loginUsername', 'class': 'input-material', 'id': 'login-username', 'data-msg': 'E-mailadres is verplicht.'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'name': 'loginPassword', 'class': 'input-material', 'id': 'login-password', 'data-msg': 'Wachtwoord is verplicht.'}))

class RegisterForm(forms.ModelForm):
    """
    The default 

    """
    email    = forms.EmailField(widget=forms.TextInput(attrs={'name': 'registerEmail', 'class': 'input-material', 'id': 'register-email', 'data-msg': 'E-mailadres is verplicht.'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'name': 'registerPassword', 'class': 'input-material', 'id': 'register-password', 'data-msg': 'Wachtwoord is verplicht.'}))
    password_2 = forms.CharField(widget=forms.PasswordInput(attrs={'name': 'registerPassword', 'class': 'input-material', 'id': 'register-password', 'data-msg': 'Wachtwoord is verplicht.'}))
 
    class Meta:
        model = User
        fields = ['email']

    def clean_email(self):
        '''
        Verify email is available.
        '''
        email = self.cleaned_data.get('email')
        qs = User.objects.filter(email=email)
        if qs.exists():
            raise forms.ValidationError("email is taken")
        return email

    def clean(self):
        '''
        Verify both passwords match.
        '''
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password_2 = cleaned_data.get("password_2")
        if password is not None and password != password_2:
            self.add_error("password_2", "Your passwords must match")
        return cleaned_data


    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user



class UpdateUserForm(forms.ModelForm):
    email = forms.EmailField(required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['email']


class UpdateProfileForm(forms.ModelForm):
    firstname = forms.CharField(max_length=100, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    lastname = forms.CharField(max_length=100, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    gender    = forms.ChoiceField(choices=Profile.GENDER_CHOICES, label='Gender', required=True, widget=forms.Select(attrs={'class':'form-control mb-3 mb-3'}))
    avatar = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control-file'}), required=False)

    class Meta:
        model = Profile
        fields = ['firstname', 'lastname', 'gender', 'avatar']



class UserAdminCreationForm(forms.ModelForm):
    """
    A form for creating new users. Includes all the required
    fields, plus a repeated password.
    """
    password = forms.CharField(widget=forms.PasswordInput)
    password_2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['email']

    def clean(self):
        '''
        Verify both passwords match.
        '''
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password_2 = cleaned_data.get("password_2")
        if password is not None and password != password_2:
            self.add_error("password_2", "Your passwords must match")
        return cleaned_data

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


class UserAdminChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ['email', 'password', 'active', 'admin']

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]

BrediusRollers/BrediusRollers/accounts/views.py
from urllib import request
from django.contrib.auth import authenticate, login
from django.views.generic import CreateView, FormView
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib import messages
from django.db.models import Sum
from django.db.models import Q


from .forms import LoginForm, RegisterForm
from .forms import UpdateUserForm, UpdateProfileForm

from django.contrib.auth.views import PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin

from PAGES.cleanup import globe
from .model.profile import Profile
from .model.adress import Adress
from teams.models import Player
from games.models import Game, Score


class LoginView(FormView):
    form_class = LoginForm
    template_name = 'login.html'
    success_url = reverse_lazy('Accounts:dashboard')

    def form_valid(self, form):
        request = self.request
        email  = form.cleaned_data.get("email")
        password  = form.cleaned_data.get("password")
        user = authenticate(request, username=email, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, 'You are now login')
            return redirect('Accounts:dashboard')
        else:
            messages.error(request, 'Invalid credentials')
            return redirect('Accounts:login')


class RegisterView(CreateView):
    form_class = RegisterForm
    template_name = 'register.html'
    success_url = reverse_lazy('Accounts:login')


@login_required
def dashboard(request):

    template = 'dashboard.html'
    current_season = globe.get_current_season()
    if current_season:
        club_name = "Bredius"
        return render(request, template, {
            })
    else:
        return render(request, template, {
            'error_message': "No current season found."
            })


    player, created = Profile.objects.get_or_create(user=request.user)  #Create empty profile for new users

    user = request.user
    profile = user.profile
    team = user.profile.player.team
    team_player = Player.objects.all().filter(team=team)
    goals = Score.objects.all().filter(player=profile.player).aggregate(Sum('goals'))
    #match_team = Match_team.objects.all().filter(team=profile.player.team)
    #amount_match = Game.objects.all().filter(Q(home_team__in=match_team) | Q(away_team__in=match_team))

    try:
        players = Player.objects.get(user=user.id)
    except:
        players = None

    context = {
        'user': user,
        'profile': profile,
        'team': team,
        'player_count': len(team_player),
        'goals': goals['goals__sum'],
        #'points': len(amount_match),
    }

    return render(request, 'dashboard.html', context)


@login_required
def team(request):
    team_player = Player.objects.all().filter(team=request.user.profile.player.team)
    profile = request.user.profile
    context = {'team_player': team_player, 'profile': profile,}
    return render(request, 'team.html', context)


@login_required
def account_games(request):
    profile = request.user.profile
    match_team = Match_team.objects.all().filter(team=profile.player.team)
    games = Game.objects.all().filter(Q(home_team__in=match_team) | Q(away_team__in=match_team)).order_by('gameday__date')       

    context = {'profile': profile, 'games': games}
    return render(request, 'account_games.html', context)



@login_required
def profile(request):
    if request.method == 'POST':

        user_form = UpdateUserForm(request.POST, instance=request.user)
        profile_form = UpdateProfileForm(request.POST, request.FILES, instance=request.user.profile)


        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Your profile is updated successfully')
            return redirect('Accounts:profile')


    else:
        user_form = UpdateUserForm(instance=request.user)
        profile_form = UpdateProfileForm(instance=request.user.profile)

    context = {
        'user_form': user_form,
        'profile_form': profile_form,
    }

    return render(request, 'profile.html', context)


class ChangePasswordView(SuccessMessageMixin, PasswordChangeView):
    template_name = 'change_password.html'
    success_message = "Successfully Changed Your Password"
    success_url = reverse_lazy('Accounts:dashboard')

BrediusRollers/BrediusRollers/accounts/templates/account_games.html
{% extends "account/account_base.html" %}
{% load static %}

{% block title %} | Goals {% endblock %}

{% block content %}


{% include 'account/_header.html' %}




<div class="d-flex align-items-stretch">
    <!-- Sidebar Navigation-->
    
    {% include 'account/_nav.html' %}

   
    
    <!-- Sidebar Navigation end-->
    <div class="page-content">
        {% include 'account/_welcome_txt.html' %}
    

        <section>
            <div class="container-fluid">
            <div class="row">
                {% for goals in goal %}
                <div class="col-lg-4">
                <div class="stats-with-chart-2 block">
                    <div class="title">
                        <strong class="d-block">{{ goals.player }}</strong>
                        <span class="d-block">{{ goals.game }}</span>
                    </div>
                    <div class="piechart chart">
                        <canvas id="pieChartHome1"></canvas>
                        <div class="text">
                            <strong class="d-block">{{ goals.goals }} goals</strong>
                            <span class="d-block">{{ goals.season }}</span>
                        </div>
                    </div>
                </div>
                </div>
                {% endfor %}
            </div>
            </div>
        </section>


<section>
    {% for game in games %}                
    <div class="public-user-block block">
        <div class="row d-flex align-items-center">   
            <div class="col-lg-4 d-flex align-items-center">
                <div class="order"></div>
                <a href="#" class="name">
                    <strong class="d-block">Wedstrijd in <strong class="text-primary">{{ game.gameday.adress.place }}</strong></strong>
                    <span class="d-block">
                        Nr.{{ game.leauge_code }} | Veld {{ game.field }} | {{ game.formated_starttime }} - {{ game.formated_endtime }}
                    </span>
                    <span>
                        <i class="icon-info"></i> {{ game.gameday.adress.get_street }}, {{ game.gameday.adress.get_zip }}
                    </span>
                </a>
            </div>
            <div class="col-lg-8 text-center">
                <div class="contributions">
                    <h4>{{ game }}</h4>
                    <strong class="text-primary">{{ game.home_score }} - {{ game.away_score }}</strong>
                </div>
                
            </div>
        </div>
    </div>
    {% endfor %}
</section>






{% include 'account/_footer.html' %}
    
{% endblock %}

BrediusRollers/BrediusRollers/accounts/templates/change_password.html
{% extends "base.html" %}
{% block content %}

<div class="form-content my-3 p-3">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                        <div class="card-header justify-content-center">
                          <h3 class="font-weight-light my-4 text-center">Change Your Password</h3>
                        </div>
                        {% if form.errors %}
                            <div class="alert alert-danger alert-dismissible" role="alert">
                                <div id="form_errors">
                                    {% for key, value in form.errors.items %}
                                        <strong>{{ value }}</strong>
                                    {% endfor %}
                                </div>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}

                        <div class="card-body">
                            <form method="POST">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                        <div class="form-group">
                                            <label class="small mb-1" for="id_old_password">Old Password</label>
                                            <input type="password" name="old_password" autocomplete="new-password"
                                                   class="form-control" required id="id_old_password"
                                                   placeholder="Enter Old Password"/>
                                            <span>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                        <div class="form-group">
                                            <label class="small mb-1" for="id_new_password1">New Password</label>
                                            <input type="password" name="new_password1" autocomplete="new-password"
                                                   class="form-control" required id="id_new_password1"
                                                   placeholder="Enter New Password"/>
                                            <span>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                        <div class="form-group">
                                            <label class="small mb-1" for="id_new_password2">New Password Confirmation</label>
                                            <input type="password" name="new_password2" autocomplete="new-password"
                                                   required id="id_new_password2" class="form-control"
                                                   placeholder="Confirm New Password"/>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                        <div class="form-group mt-0 mb-1">
                                            <button type="submit" class="col-md-12 btn btn-dark" id="reset">Update Password</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

BrediusRollers/BrediusRollers/accounts/templates/login.html
{% extends "account/account_base.html" %}

{% block title %} | Login {% endblock %}
{% block content %}
  
<div class="login-page">
  <div class="container d-flex align-items-center">
      <div class="form-holder has-shadow">
          <div class="row">
              
              <!-- Form Panel    -->
              <div class="col-lg-6 bg-white">
                  <div class="form d-flex align-items-center">
                      <div class="content">
                          <form method="POST" class="form-validate">
                              {% csrf_token %}

                              <div class="form-group">
                                  {{ form.email }}
                                  <label for="login-username" class="label-material">E-mailadres</label>
                              </div>

                              <div class="form-group">
                                  {{ form.password }}
                                  <label for="login-password" class="label-material">Wachtwoord</label>
                              </div>

                              <button type='submit' id="login" class='btn btn-primary'>Log in</button>
                          </form>
                          <a href="{% url 'Accounts:password_change' %}" class="forgot-pass">Wachtwoord vergeten?</a>
                          <br>
                          <small>Heb je geen account? </small><a href="{% url 'Accounts:register' %}" class="signup">Aanmelden</a>
                      </div>
                  </div>
              </div>

              <!-- Logo & Information Panel-->
              <div class="col-lg-6">
                <div class="info d-flex align-items-center">
                    <div class="content">
                        <div class="logo">
                            <h1>Login</h1>
                        </div>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                        <a href="{% url 'Pages:home' %}" class='btn btn-dark'>Terug naar home</a>
                    </div>
                </div>
              </div>


          </div>
      </div>
    <div class="copyrights text-center">
        <p>2018 &copy; Your company. Download From <a target="_blank" href="https://templateshub.net">Templates Hub</a>.</p>
    </div>
  </div>
</div>






{% endblock %}


<div class="login-page">
    <div class="container d-flex align-items-center">
        <div class="form-holder has-shadow">
            <div class="row">
                <!-- Logo & Information Panel-->
                <div class="col-lg-6">
                    <div class="info d-flex align-items-center">
                        <div class="content">
                            <div class="logo">
                                <h1>Dashboard</h1>
                            </div>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                        </div>
                    </div>
                </div>
                <!-- Form Panel    -->
                <div class="col-lg-6 bg-white">
                    <div class="form d-flex align-items-center">
                        <div class="content">
                            <form method="get" class="form-validate">
                                <div class="form-group">
                                    <input id="login-username" type="text" name="loginUsername" required data-msg="Please enter your username" class="input-material">
                                    <label for="login-username" class="label-material">User Name</label>
                                </div>
                                <div class="form-group">
                                    <input id="login-password" type="password" name="loginPassword" required data-msg="Please enter your password" class="input-material">
                                    <label for="login-password" class="label-material">Password</label>
                                </div>
                                <a id="login" href="index.html" class="btn btn-primary">Login</a>
                                <!-- This should be submit button but I replaced it with <a> for demo purposes-->
                            </form><a href="#" class="forgot-pass">Forgot Password?</a><br><small>Do not have an account? </small><a href="register.html" class="signup">Signup</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="copyrights text-center">
        <p>2018 &copy; Your company. Download From <a target="_blank" href="https://templateshub.net">Templates Hub</a>.</p>
    </div>
</div>

BrediusRollers/BrediusRollers/accounts/templates/register.html
{% extends "account/account_base.html" %}

{% block title %} | Register {% endblock %}
{% block content %}

<div class="login-page">
  <div class="container d-flex align-items-center">
    <div class="form-holder has-shadow">
      <div class="row">
        <!-- Logo & Information Panel-->
        <div class="col-lg-6">
          <div class="info d-flex align-items-center">
              <div class="content">
                  <div class="logo">
                      <h1>Registeren</h1>
                  </div>
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                  <a href="{% url 'Pages:home' %}" class='btn btn-dark'>Terug naar home</a>
              </div>
          </div>
        </div>
        <!-- Form Panel    -->
        <div class="col-lg-6 bg-white">
          <div class="form d-flex align-items-center">
            <div class="content">
              <form method='POST' class="text-left form-validate">
                {% csrf_token %}

                <div class="form-group-material">
                  {{ form.first_name }}
                  <label for="register-username" class="label-material">Voornaam</label>
                </div>
                <div class="form-group-material">
                  {{ form.email }}
                  <label for="register-email" class="label-material">E-mailadres</label>
                </div>
                <div class="form-group-material">
                  {{ form.password }}
                  <label for="register-password" class="label-material">Wachtwoord</label>
                </div>
                <div class="form-group-material">
                  {{ form.password_2 }}
                  <label for="register-password" class="label-material">Bevestig Wachtwoord</label>
                </div>
                <div class="form-group terms-conditions text-center">
                  <input id="register-agree" name="registerAgree" type="checkbox" required value="1" data-msg="Uw toestemming is vereist" class="checkbox-template">
                  <label for="register-agree">Ik ga akkoord met de voorwaarden en het beleid</label>
                </div>
                <div class="form-group text-center">
                  <button type='submit' id="register" class='btn btn-primary'>Registreer nu</button>
                </div>
              </form>
              
                <small>Heb je al een account? </small><a href="{% url 'Accounts:login' %}" class="signup">Log in</a>
                
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="copyrights text-center">
    <p>2018 &copy; Your company. Download From <a target="_blank" href="https://templateshub.net">Templates Hub</a>.</p>
  </div>
</div>




{% endblock %}