BrediusRollers/BrediusRollers/Core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('PAGES.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns() 

BrediusRollers/BrediusRollers/PAGES/urls.py
from django.urls import path
from . import views

app_name='Pages'

urlpatterns = [
    path('', views.home, name='home'),
    path('wedstrijden', views.wedstrijden, name='wedstrijden'),
    path('wedstrijden/<int:game_id>', views.wedstrijd, name='wedstrijd'),
    path('teams', views.teams, name='teams'),
    path('teams/<int:player_id>', views.player, name='player'),
    path('over-ons', views.overons, name='overons'),
    path('contact', views.contact, name='contact'),
]

BrediusRollers/BrediusRollers/teams/models.py
from django.contrib import admin
from django.db import models
from django.urls import reverse
from multiselectfield import MultiSelectField
from accounts.model.profile import Profile
from club.models import Season, Club, Coach
from datetime import date

class League(models.Model):
    LEAGUE_CHOICES = [
        ('Hoofdklasse', 'Hoofdklasse'),
        ('Overgangsklasse', 'Overgangsklasse'),
        ('Eerste Klasse', 'Eerste Klasse'),
        ('Tweede Klasse', 'Tweede Klasse'),
        ('Derde Klasse', 'Derde Klasse'),
        ('Vierde Klasse', 'Vierde Klasse'),
    ]
    name = models.CharField(choices=LEAGUE_CHOICES, max_length=50, verbose_name="League")
    def __str__(self):
        return self.name

class Team(models.Model):
    club = models.ForeignKey(Club, on_delete=models.CASCADE, null=True, blank=True, verbose_name="Club", limit_choices_to={'season__start_date__lte': date.today(), 'season__end_date__gte': date.today()})
    league = models.ForeignKey('teams.League', on_delete=models.CASCADE, verbose_name="League")
    name  = models.CharField(max_length=255, verbose_name="Team")
    
    points_earned  = models.IntegerField(verbose_name="Earned Points")
    matches_played  = models.IntegerField(verbose_name="Played Matches")
    coach = models.ForeignKey(Coach, on_delete=models.CASCADE, null=True, blank=True, verbose_name="Coach", limit_choices_to={'season__start_date__lte': date.today(), 'season__end_date__gte': date.today()})

    def __str__(self):
        return f"{self.club} {self.name}"

    def get_name(self):
        return f"{self.club.name} {self.name}"

    def get_absolute_url(self):
        return reverse('Pages:team_filter', args=[self.id])

class Player(models.Model):
    POSITION_CHOICES = [
        ('middenvelder', 'Middenvelder'),
        ('aanvaller', 'Aanvaller'),
        ('verdediger', 'Verdediger'),
        ('goalkeeper', 'Goalkeeper'),
    ]

    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True, verbose_name="Profile")
    team = models.ForeignKey(Team, on_delete=models.CASCADE, null=True, blank=True, verbose_name="Team", limit_choices_to={'club__season__start_date__lte': date.today(), 'club__season__end_date__gte': date.today()})
    positions = MultiSelectField(choices=POSITION_CHOICES, verbose_name="Positions")
    number_plate  = models.IntegerField(verbose_name="Number plate")

    is_captain  = models.BooleanField(blank=True, verbose_name="captain")

    def __str__(self):
        return self.profile.firstname + ' ' + self.profile.lastname

    def calculate_total_goals_current_season(self):
        current_date = date.today()
        current_season = Season.objects.get(start_date__lte=current_date, end_date__gte=current_date)
        return self.score_set.filter(season=current_season).aggregate(total_goals=models.Sum('goals'))['total_goals']

BrediusRollers/BrediusRollers/PAGES/templates/overons.html
{% extends 'base.html' %}
{% load static %}

{% block title %} | OverOns {% endblock %}

{% block content %}


<!--TROPHEY ROOM BEGIN-->
<section class="trophey-room">
    
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h4>Club informatie</h4> 
            </div>

            
            <div class="col-md-7">
                <div class="trophey-media">
                    <img src="{{ club.picture.url }}" alt="club-image">
                </div>
            </div>
            <div class="col-md-5">
                <ul class="done-list">
                    <!-- <li>Win a championship</li>
                    <li>Played 96 matches</li>
                    <li>Have not lost a single match at home</li>
                    <li>New club record for most scores</li> -->
                    <li>Leeftijd en beperking vormen geen belemmering: bij ons is <strong>iedereen welkom</strong>!</li>
                    <li>Ontdek de <strong>spanning en sportiviteit</strong> van Rolstoelhockey: een uitdagende teamsport met techniek en tactiek.</li>
                    <li>Geniet van een <strong>vertrouwelijke sfeer</strong> waarin je op je eigen niveau kunt spelen, met ondersteuning om naar de top te komen.</li>
                    <li><strong>Prestaties en teamspel</strong> gaan hand in hand bij onze club: ervaar het zelf en ontdek hoe ver je kunt komen!</li>
                    <li>Bij ons draait alles om <strong>passie en plezier</strong>: ontdek hoe je met jouw talenten het beste uit jezelf kunt halen!</li>
                </ul>
            </div>
            <div class="col-md-12">
                <p>
                    {{ club.description }}
                </p>
            </div>

        </div>
    </div>

    <!--TIMELINE BEGIN-->
    <div class="timeline-bar">
        <div class="bar">
            <div class="date date-1" ></div>
            <div class="date date-2" ></div>
            <div class="date date-3" ></div>
            <div class="date date-4" ></div>
            <div class="date date-5" ></div>
            <div class="date date-6 active" ></div>
        </div>
                
        <script>
            const firstYear = 2015;
            const currentYear = new Date().getFullYear();
            const numYears = currentYear - firstYear + 1;
            const step = Math.floor(numYears / 5);
        
            const yearDivs = document.querySelectorAll('.date');
        
            yearDivs[0].textContent = firstYear;
            yearDivs[yearDivs.length - 1].textContent = currentYear;
        
            for (let i = 1; i < yearDivs.length - 1; i++) {
                const year = firstYear + i * step;
                yearDivs[i].textContent = year;
            }
        </script>
    </div>
    <!--TIMELINE END-->
    
</section>
<!--TROPHEY ROOM END-->


<!--CLUB WRAP BEGIN-->
<section class="club-wrap">
    <div class="container">
        <div class="row row-eq-height">
            <div class="col-md-9 col-sm-9 col-xs-9">
                <h4>{{ club.name }}</h4>
            </div>
            <div class="col-md-3 col-sm-3 col-xs-3">
                <a href="{% url 'Pages:contact' %}" class="btn small club-top-btn">Versterk jij ons team?</a>
            </div>
        </div>
    </div>
    <div class="club-top-info">
        <div class="organisation-header-wrapper">
            <div class="container">
                <div class="tab-content">
                    <div class="tab-pane active" id="all">
                        <div class="row">
                            <div class="col-md-5">
                                <div class="club-logo  wpb_animate_when_almost_visible wpb_zoomInLeft zoomInLeft wpb_start_animation animated">
                                    <img class="img-responsive" src="{% static 'images/icons/ball.png' %}" alt="organisation logo" >                
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="org-club-info">                                    
                                    <div class="item"><span>Seizoen:</span> {{ club.season.start_date|date:"M Y" }} - {{ club.season.end_date|date:"M Y" }}</div>
                                    <div class="item"><span>Onze teams:</span> {{ teamnames }}</div>  
                                    <div class="item"><span>Plaats:</span> {{ club.city }}</div>
                                    <div class="item"><span>Trainingen gehad:</span> {{ training_count }}</div>
                                    <div class="item"><span>Aantal leden:</span> {{ member_count }}</div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="org-club-stat">      
                                    {% if next_training %}
                                    <div class="title">aankomend training | <strong id="training-countdown-box"></strong></div>
                                    <div class="next">
                                        <div class="info">
                                            <div class="name" id="training-countdown">{{ next_training.date|date:"l" }} {{ next_training.training_time.start_time|date:"H:i" }} | {{ next_training.date|date:"d M Y" }}</div>
                                            <div class="date">{{ next_training.training_location.adress.street }} {{ next_training.training_location.adress.house_number }} | {{ next_training.training_location.adress.zipcode }} {{ next_training.training_location.adress.zipcode_number }} {{ next_training.training_location.adress.place }}</div>
                                            <div class="date">Start tijd {{ next_training.training_time.start_time|date:"H:i" }} | Eind tijd {{ next_training.training_time.end_time|date:"H:i" }}</div>
                                            <div class="date">Opbouw ca. 30min | Afbouw ca. 30min</div>
                                        </div>
                                    </div>
                                   {% endif %}
                                    
                                    <!-- <div class="title">team stats</div>
                                    <div class="circle-item">
                                        <div class="circle-bar" id="circle_3" data-percent="55"></div>
                                        <div class="text">Winst </div>
                                    </div>
                                    <div class="circle-item">
                                        <div class="circle-bar" id="circle_4" data-percent="37"></div>
                                        <div class="text">Lost </div>
                                    </div>              -->
                                </div>
                            </div>
                        </div>	
                    </div>
                </div>
            </div>	
        </div>
    </div>
</section>
<!--CLUB WRAP END-->



{% if photos %}
<!--MACTH LIVE GALLERY BEGIN-->
<section class="match-live-gallery">
    <div class="owl-carousel owl-theme gallery-slider">
        {% for photo in photos %}
        <div class="item">
            <a href="javascript:void(0);">
                <span class="info">
                    <span class="then">{{ photo.title }}</span>
                    <span class="what">{{ photo.description }}</span>
                </span>
                <img src="{{ photo.photo.url }}" alt="{{ photo.title }}">
            </a>
        </div>
        {% endfor %}
    </div>
    <div class="container">
        <div class="row">
            <div class="col-xs-6"></div>
            <div class="col-xs-6 text-right">
                <div class="owl-carousel-arrows">
                    <div class="custom-navigation">
                        <a class="custom-next-btn"><i class="fa fa-caret-left fa-3x" aria-hidden="true"></i></a>
                        <a class="custom-prev-btn"><i class="fa fa-caret-right fa-3x" aria-hidden="true"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--MACTH LIVE GALLERY END-->
{% endif %}


<!-- Bredius Team -->
{% include 'import/_brediusTeam.html' %}
<!-- Bredius Team End -->


<!-- Call to action -->
{% include 'import/_call2action.html' %}
<!-- Become part of a great team -->


<!--SPONSOR BOX BEGIN-->
{% include 'import/_sponsor.html' %}
<!--SPONSOR BOX END-->



{% endblock %}

BrediusRollers/BrediusRollers/PAGES/templates/player.html
{% extends 'base.html' %}
{% load static %}

{% block title %} | Players {% endblock %}

{% block content %}

<section class="player-single-wrap">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="player-photo">
                    <div class="number">{{ player.number_plate }}</div>
                    <img class="img-responsive" src="{{ player.profile.profiel.url }}" alt="player">
                </div>  
            </div>

            <div class="col-md-8">

                <div class="col-md-12">
                    {% if player.is_captain %}
                    <div class="captain-bage">Captain</div>
                    {% endif %}

                    <h4 class="player-name">
                        
                        {% if player.profile.gender %}
                        {{ player.profile.gender }}. 
                        {% endif %}
                    
                        {{ player.profile.lastname }} 
                    </h4>

                </div>

                
                <div class="col-md-6">
                    <div class="player-info">
                        <h6 class="player-info-title">overzicht</h6>	
                        <div class="summary">
                            <div class="row">
                                <div class="col-md-4 col-sm-4 col-xs-4">
                                    <div class="item">Naam:</div>
                                </div>
                                <div class="col-md-8 col-sm-8 col-xs-8">{{ player.profile.get_full_name }}</div>
                                <div class="col-md-4 col-sm-4 col-xs-4">
                                    <div class="item">Positie:</div>
                                </div>
                                <div class="col-md-8 col-sm-8 col-xs-8">{{ player.positions }}</div>
                                <div class="col-md-4 col-sm-4 col-xs-4">
                                    <div class="item">Team:</div>
                                </div>
                                <div class="col-md-8 col-sm-8 col-xs-8">{{ player.team.get_name }}</div>
                                <div class="col-md-4 col-sm-4 col-xs-4">
                                    <div class="item">Seizoen:</div>
                                </div>
                                <div class="col-md-8 col-sm-8 col-xs-8">{{ player.team.club.season.start_date|date:"Y" }} - {{ player.team.club.season.end_date|date:"Y" }}</div>
                            </div>
                        </div>
                        

                        <!-- <h6>Trofeeën</h6>
                        <ul class="player-trophey">
                            <li>
                                <img src="images/common/am-trophey1.png" width="100" height="150" alt="trophy">
                                <div class="year">2012</div>
                            </li>
                            <li>
                                <img src="images/common/am-trophey.png" width="100" height="150" alt="trophy">
                                <div class="year">2015</div>
                            </li>
                            <li>
                                <img src="images/common/am-trophey2.png" width="100" height="150" alt="trophy">
                                <div class="year">2017</div>
                            </li>
                        </ul>
                         -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


{% endblock %}

BrediusRollers/BrediusRollers/PAGES/templates/teams.html
{% extends 'base.html' %}
{% load static %}

{% block title %} | Teams {% endblock %}

{% block content %}

{{ bred }}


<!--CLUB STAFF TOP BEGIN-->
<div class="club-staff-top">
    <div class="container">
        <div class="row">
            {% for team, players in team_players.items %}
                <div class="col-md-12">
                    <h4>{{ team.get_name }}</h4>
                </div>
                {% for player in players %}
                <div class="staff-box">            
                    <div class="col-md-3  col-sm-6 col-xs-12">
                        <a href="{% url 'Pages:player' player.id %}" class="item">
                            <span class="info">
                                <span class="name">{{ player.profile.get_full_name }}</span>
                                <span class="position">{{ player.positions }}</span>
                                <span class="number">{{ player.number_plate }}</span>
                            </span>
                            <img src="{{ player.profile.profiel.url }}" alt="player">
                        </a>
                    </div>                                         
                </div>
                {% endfor %}
            {% endfor %}      
        
            <!-- <div class="col-md-12">
                <p>Pabst irony tattooed, synth sriracha selvage pok pok. Wayfarers kinfolk sartorial, helvetica you probably haven't heard of them tumeric venmo deep v mixtape semiotics brunch. </p>
            </div> -->
        </div>
    </div>
</div>
<!--CLUB STAFF TOP END-->

<!-- Bredius Team -->
{% include 'import/_brediusTeam.html' %}
<!-- Bredius Team End -->

<!--SPONSOR BOX BEGIN-->
{% include 'import/_sponsor.html' %}
<!--SPONSOR BOX END-->

{% endblock %}

BrediusRollers/BrediusRollers/PAGES/templates/wedstrijd.html
{% extends 'base.html' %}
{% load static %}

{% block title %} | Wedstrijd {% endblock %}

{% block content %}

<!--MATCH PAGE TOP BEGIN-->
<div class="match-page-top">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="upcoming-match-info">
                    <div class="team">
                        <!-- <div class="avatar"><img src="images/soccer/team-logo1.png" alt="match-list-team-img"></div> -->
                        <div class="text">
                            {{ game.home_team.get_name }}
                            {% if game.home_team.club.city %}<span>{{ game.home_team.club.city }}</span>{% endif %}
                        </div> 
                    </div>
                    <div class="counter">
                        <ul>
                            <li><div class="digit">{{ game.home_score|default:"?" }}</div></li>
                            <li><div class="digit">{{ game.away_score|default:"?" }}</div></li>
                        </ul>
                    </div>
                    <div class="team right">
                        <div class="text">
                            {{ game.away_team.get_name }} 
                            <span>{{ game.away_team.club.city }}</span>
                        </div>
                        <!-- <div class="avatar"><img src="images/soccer/team-logo2.png" alt="match-list-team-img"></div> -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!--MATCH PAGE TOP END-->



<!--LIVE MACTH STAT BEGIN-->

<section class="live-match-stat">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <!-- <h6>Wedstrijd details</h6>
                <div class="live-details">Chia celiac street art, raclette bespoke biodiesel try-hard chillwave kinfolk art party. Raclette salvia mumblecore roof party locavore. Normcore man braid snackwave. Tacos coloring book everyday carry farm-to-table forage. Chillwave vaporware la croix keytar lyft disrupt jianbing squid normcore venmo gochujang etsy. Cred tote bag retro, enamel pin put a bird on it af irony scenester.</div> -->
                <div class="statistics">
                    <div class="col-lg-6">
                        <h6>Wedstrijd details</h6>
                        <p>
                            {{ game.gameday.date|date:"d F Y"|lower }} <br />
                            Code: {{ game.leauge_code }} | Veld {{ game.field }} | {{ game.league.name }}<br />
                            Tijd: {{ game.start_time|time:"H:i" }} tot {{ game.end_time|time:"H:i" }} uur 
                        </p>
                    </div>

                    <div class="col-lg-6">
                        <h6>weervoorspelling</h6>
                        <p>Binnenkort</p>
                        <!-- <div class="live-match-weather">
                            <div class="icon">
                                <img src="images/common/wether-sun.png" alt="wether-sun">
                            </div>	
                            <div class="info">
                                <div class="degree">7 °C</div>
                                <div class="text">Partly cloudy night</div>
                            </div>
                        </div> -->
                    </div>

                    <div class="col-lg-12">
                        <h6>Wedstrijd Locatie</h6>
                        <div class="arena">
                            <!-- <div class="img-wrap">
                                <div class="title">{{ game.gameday.sport_hall }}</div>
                                <img src="images/soccer/arena-img.jpg" alt="arena-img">
                            </div> -->
                            <div class="arena-info">
                                <div class="name">Sporthal {{ game.gameday.sport_hall }}</div>
                                <div class="date">{{ game.gameday.adress.get_street }}, {{ game.gameday.adress.get_zip }}</div>

                                <iframe width="100%" height="250" src="https://maps.google.com/maps?q={{ game.gameday.adress.get_street }},%20{{ game.gameday.adress.get_zip }}&t=&z=13&ie=UTF8&iwloc=&output=embed"></iframe>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-4">
                <h6>Verwachte Opstelling</h6>
                <div class="match-lineup">
                    <div class="no-gutter">
                        <div class="col-lg-12">
                            <div class="head">
                                <div class="name">Team spelers</div>
                            </div>
                            <div class="team-wrap">	
                                {% for player in players %}
                                <div class="member">
                                    <a href="{% url 'Pages:player' player.id %}" class="avatar">
                                        <img src="{{ player.profile.profiel.url }}" alt="player-avatar">
                                    </a>

                                    <div class="info">
                                        <div class="wrap">
                                            <a href="{% url 'Pages:player' player.id %}" class="name">
                                                {{ player.profile.get_full_name }} {% if player.is_captain %} | Captain {% endif %} <br />
                                                {% if player.positions %}<small>{{ player.positions }}</small>{% endif%} <br />
                                                
                                            </a>
                                            <!-- <img src="images/common/timeline-goal.jpg" alt="timeline-goal"> -->
                                        </div>
                                        <!-- <div class="country"><img src="images/common/en-flag.png" alt="v">Ukraine</div> -->
                                    </div>
                                </div>
                                {% endfor %}
                               
                            </div>
                        </div>
                    </div>					
                </div>


                <!-- <h6>Coach</h6>
                <div class="match-lineup">
                <div class="no-gutter">
                    <div class="col-md-12">
                        <div class="team-wrap">	


                            <div class="member">
                                <a href="player.html" class="avatar">
                                    <img src="images/common/member-avatar.jpg" alt="member-avatar">
                                </a>
                                <div class="info">
                                    <div class="wrap">
                                        <a href="#" class="name">test test a</a>
                                    </div>
                                    <div class="country"><img src="images/common/en-flag.png" alt="flag">Ukraine</div>
                                </div>
                            </div>

                        </div>	
                    </div>
                </div>
                </div> -->

            </div>
        </div>
    </div>
</section>

<br />
<!--LIVE MACTH STAT END-->


<!--SHARE BOX BEGIN-->
<!-- 
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="share-box">
                <div class="item">
                    <div class="container-fluid">
                        <div class="row no-gutter">
                            <div class="col-md-4 col-sm-6 col-xs-12">
                                <div class="title">SHARE THIS MATCH</div>
                            </div>
                            <div class="col-md-8 col-sm-6 col-xs-12 text-right">
                                <ul class="share-socials  wpb_animate_when_almost_visible wpb_fadeInRight fadeInRight wpb_start_animation animated">                        

                                    <li class="digg">
                                        <a href="http://www.digg.com/">
                                            <i class="fa fa-digg" aria-hidden="true"></i>
                                        </a>
                                    </li>

                                    <li class="facebook">
                                        <a href="http://www.facebook.com/">
                                            <i class="fa fa-facebook-square" aria-hidden="true"></i>
                                        </a>
                                    </li>

                                    <li class="google">
                                        <a href="https://plus.google.com/">
                                            <i class="fa fa-google-plus-square" aria-hidden="true"></i>
                                        </a>
                                    </li>

                                    <li class="linkedin">
                                        <a href="http://www.linkedin.com/">
                                            <i class="fa fa-linkedin-square" aria-hidden="true"></i>
                                        </a>
                                    </li>

                                    <li class="pinterest">
                                        <a href="http://assets.pinterest.com/">
                                            <i class="fa fa-pinterest-square" aria-hidden="true"></i>
                                        </a>
                                    </li>

                                    <li class="reddit">
                                        <a href="http://reddit.com/">
                                            <i class="fa fa-reddit-square" aria-hidden="true"></i>
                                        </a>
                                    </li>

                                    <li class="StumbleUpon">
                                        <a href="http://www.stumbleupon.com/">
                                            <i class="fa fa-stumbleupon-circle" aria-hidden="true"></i>
                                        </a>
                                    </li>

                                    <li class="tumbler">
                                        <a href="http://www.tumblr.com/">
                                            <i class="fa fa-tumblr-square" aria-hidden="true"></i>
                                        </a>
                                    </li>

                                    <li class="twitter">
                                        <a href="https://twitter.com/">
                                            <i class="fa fa-twitter-square" aria-hidden="true"></i>
                                        </a>
                                    </li>

                                    <li class="vk">
                                        <a href="http://vkontakte.ru/">
                                            <i class="fa fa-vk" aria-hidden="true"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div>
</div> -->

<!--SHARE BOX END-->


{% endblock %}