BrediusRollers/BrediusRollers/Core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('PAGES.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns() 

BrediusRollers/BrediusRollers/PAGES/urls.py
from django.urls import path
from . import views

app_name='Pages'

urlpatterns = [
    path('', views.home, name='home'),
    path('wedstrijden', views.wedstrijden, name='wedstrijden'),
    path('wedstrijden/<int:game_id>', views.wedstrijd, name='wedstrijd'),
    path('teams', views.teams, name='teams'),
    path('teams/<int:player_id>', views.player, name='player'),
    path('over-ons', views.overons, name='overons'),
    path('contact', views.contact, name='contact'),
]

BrediusRollers/BrediusRollers/accounts/urls.py
from django.urls import path
from . import views
from accounts.views import LoginView, RegisterView
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView

app_name='Accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/', views.profile, name='profile'),
    path('team/', views.team, name='team'),
    path('account_games/', views.account_games, name='account_games'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password-change/', views.ChangePasswordView.as_view(), name='password_change'),
]

BrediusRollers/BrediusRollers/templates/partials/_alerts.html
{% if messages %}
{% for message in messages %}
    <div id="message" class="container">

        <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="allert">
            <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
            <strong>
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                    Error:
                {% else %}
                    {{ message.tags|title }}
                {% endif %}
            </strong>
            {{ message }}
        </div>
    </div>
{% endfor %}
{% endif %}

BrediusRollers/BrediusRollers/templates/partials/_footer.html
{% load static %}

<footer class="footer">
    <div class="wrapper-overfllow">
        <div class="container">
            <div class="row">
                <div class="col-md-5 col-sm-12">
                    <div class="footer-left">
                        <div class="wrap">
                            <a href="index-2.html" class="foot-logo"><img src="{% static 'images/site/midium_white_logo.png' %}" alt="BrediusRollers-logo"></a>
                            <p>Bij het handbewogen rolstoelhockey mag iedereen deelnemen met of zonder beperking en is voor alle leeftijden.</p>
                            <!-- <ul class="foot-left-menu">
                                <li><a href="staff.html">First team</a></li>
                                <li><a href="staff.html">Second team</a></li>
                                <li><a href="amateurs.html">Amateurs</a></li>
                                <li><a href="donations.html">Donation</a></li>
                                <li><a href="trophies.html">trophies</a></li>
                            </ul> -->
                            <a href="https://wa.me/31631027637">Versterk jij ons team?</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-2 col-sm-12 col-lg-offset-1">
                    <!-- <div class="foot-news">
                        <h4>Recent news</h4>
                        <div class="item">
                            <a href="news.html" class="image"><img class="img-responsive" src="{% static 'other/images/soccer/foot-news-img.jpg' %}" alt="news-image"></a>
                            <a href="news.html" class="name">When somersaulting Sanchez shouldered Mexico’s hopes</a>
                            <a href="news.html" class="date">25 Sep 2016</a>
                            <span class="separator">in</span>
                            <a href="news.html" class="category">Highlights</a>
                        </div>
                    </div> -->
                </div>
                <div class=" col-lg-4 col-md-5 col-sm-12">
                    <div class="foot-contact">
                        <h4>Contact</h4>
                        <ul class="contact-list">
                            <!-- Import social icons -->
                            {% include 'import/_social_icons.html' %}
                        </ul>

                    </div>
                </div>
            </div>
            

            
            
            <a href="#top" class="foot-up"><span>Top <i class="fa fa-caret-up" aria-hidden="true"></i></span></a>
        
        </div>
    </div>
    
    <!-- DOCS HERE -->
    <!-- <div class="footer-menu-wrap">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <ul class="footer-menu">
                        <li class="active"><a href="index-2.html"><span>Home</span></a></li>
                        <li><a href="matches.html"><span>Matches</span></a></li>
                        <li><a href="staff.html"><span>Team</span></a></li>
                        <li><a href="news.html"><span>News</span></a></li>
                        <li><a href="store.html"><span>Store</span></a></li>
                        <li><a href="contacts.html"><span>Contact</span></a></li>
                    </ul>	
                    
                </div>
            </div>
        </div>
    </div> -->
    <div class="footer-bottom">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="copyrights text-center">
                        &copy; <script>document.write(new Date().getFullYear())</script> 
                        Bredius Rollers. Alle rechten voorbehouden |
                        <a target="_blank" href="https://www.templateshub.net">Templates Hub</a>
                        Mogelijk door 
                        <a rel="nofollow" href="https://webresolute.com/" target="_blank">WebResolute</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

BrediusRollers/BrediusRollers/templates/partials/_nav.html
{% load static %}

{% url 'Pages:home' as home %}
{% url 'Pages:wedstrijden' as wedstrijden %}
{% url 'Pages:teams' as teams %}
{% url 'Pages:overons' as overons %}
{% url 'Pages:contact' as contact %}
{% url 'Accounts:dashboard' as login %}

<div class="main-menu-wrap sticky-menu">
    <div class="container">
        <a href="{{ home }}" class="custom-logo-link"><img src="{% static 'images/site/small_white_logo.png' %}" alt="logo" class="custom-logo"></a>
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#team-menu" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <nav class="navbar">
            <div class="collapse navbar-collapse" id="team-menu">
                <ul class="main-menu nav">

                    <li {% if request.path == home %}class="active"{% endif %}>
                        <a href="{{ home }}"><span>Home</span></a>
                    </li>


                    <li {% if request.path == wedstrijden %}class="active"{% endif %}>
                        <a href="{{ wedstrijden }}"><span>Wedstrijden</span></a>
                    </li>

                    <li {% if request.path == teams %}class="active"{% endif %}>
                        <a href="{{ teams }}"><span>Teams</span></a>
                    </li>
                    
                    <li {% if request.path == overons %}class="active"{% endif %}>
                        <a href="{{ overons }}"><span>Over ons</span></a>
                    </li>

                    <li {% if request.path == contact %}class="active"{% endif %}>
                        <a href="{{ contact }}"><span>Contact</span></a>
                    </li>

                    <!-- <li {% if request.path == login %}class="active"{% endif %}>
                        <a href="{{ login }}"><span><i class="fa fa-user"></i></span></a>
                    </li>                     -->
                </ul>
            </div>       
        </nav>
    </div>
</div>

BrediusRollers/BrediusRollers/templates/partials/_topbar.html
{% load static %}

<div class="top-bar">
    <div class="container">
        <div class="row">
            <div class="col-md-7 hidden-sm hidden-xs">
                <div class="top-contacts">

                    <ul class="socials">
                        {% include 'import/_social_icons.html' %}
                        <!-- Import social icons -->
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>